// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cenconApi.Data;

#nullable disable

namespace cenconApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cenconApi.Model.ReqOpenClose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JReqClose")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("JReqOpen")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Jam")
                        .HasColumnType("datetime2");

                    b.Property<string>("KDClose")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NOWO")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<string>("WSID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NOWO");

                    b.HasIndex("Tanggal");

                    b.HasIndex("WSID");

                    b.ToTable("ReqOpenClose");
                });

            modelBuilder.Entity("cenconApi.Model.ViewForm.ViewOrderCenconResult", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("JReqClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JReqOpen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Jam")
                        .HasColumnType("datetime2");

                    b.Property<string>("KDClose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NMCABANG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOWO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<string>("WSID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
